In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])


In [4]:
print(a+b)

[3 5 7 9]


In [5]:
print(a-b)

[-1 -1 -1 -1]


In [9]:
a=a/b

In [12]:
np.array(a,dtype=np.int8)

array([0, 0, 0, 0], dtype=int8)